name:                stagedregex
version:             0.1.0.0
github:              "Xenosi/Staged-regex-Haskell"
license:             BSD3
author:              "Yannick Van Eylen"
maintainer:          "yannick.student@kuleuven.be"
copyright:           "2021 Yannick Van Eylen

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Xenosi/Staged-regex-Haskell#readme>

dependencies:
- base >= 4.7 && < 5
- criterion
- template-haskell
- containers
- regex-tdfa
- regex-pcre

library:
  source-dirs: src

executables:
  regex-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stagedregex

tests:
  regex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stagedregex
